### ISSUE TITLE
covariates

### ISSUE THREAD

**Issue by shimbalama** [mgalardini/pyseer#29] opened 2018-02-05 05:03 UTC
Hi Marco,

I've been trying to use covariates and I have a few issues. First I get this error when using '--use-covariates':

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/pyseer", line 11, in <module>
    load_entry_point('pyseer==0.3.1', 'console_scripts', 'pyseer')()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pyseer/__main__.py", line 162, in main
    p)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pyseer/input.py", line 97, in load_covariates
    sys.stderr.write('Covariates columns values should be > 1 and lower ' +
NameError: name 'sys' is not defined

Not sure why its throwing that as 'sys' is clearly imported. Might be a system specific issue for me. 

The main problem I have is that I don't understand your -h for '--use-covariates':

--use-covariates [USE_COVARIATES [USE_COVARIATES ...]]
                        Covariates to use. Format is "2 3q 4" (q for
                        quantitative) [Default: load covariates but don't use
                        them]
Can you please elaborate on 'Format is "2 3q 4" '?

The error that fails above would tell me 'Covariates columns values should be > 1 and lower than total number of columns (3)'. Which for me only leaves 2 as an option. I've modelled my covariates file on the example (covariates.txt) you give in the test folder. Tab separated [sample, sample count/number, covar]. I have 1 covar (country) that has 18 options (UK, US, Australia etc..).

Calling it as 'nice pyseer kmers.txt.gz invasive2.txt snp_dist.tsv --min-af 0.01 --max-af 0.99 --cpu 44 --filter-pvalue 1E-2 --max-dimensions 2 --covariates co_vars.txt --use-covariates 2' I get 'Matrix inversion error for null model. Could not fit null model, exiting'

**Comment by mgalardini** [comment] 2018-02-05 09:03
Hi Liam,

Sorry to hear you encountering some trouble; I could reproduce the first error, and I just pushed a new version that fixes it and produces a clearer error message. You can install it trough pip. You are right that the error message should say that you have to provide a column number that should be "equal or lower than 3".

Your covariate is categorical, and I believe you are getting the Matrix inversion error because it leads to a perfectly separable matrix for the logistic regression. Could you try with a coarser categorization (leading to a lower number of classes)?

Hope this helps,
Marco

**Comment by shimbalama** [comment] 2018-02-06 05:39
Hi Marco,

I have 18 countries that I'm using as covars. How can I make that a coarser
categorisation? Maybe use continents? 18 covars for ~1300 samples seems
relatively course already.

Thanks.
Liam

**Comment by johnlees** [comment] 2018-02-06 14:37
This might be a problem with the rank of the regression, though I thought we had this in one of our tests. Did we remove one of the categories when a covariate is supplied? I'll check the code

@shimbalama could you attach your `invasive2.txt`,  `snp_dist.tsv` and `co_vars.txt` as a .tar here and I'll take a look?

@mgalardini did you push to first fix to both master and version2? We should make sure it's merged into both

**Comment by mgalardini** [comment] 2018-02-06 15:00
Hi @johnlees, yes we should be removing one of the categories when dummy encoding a covariate, as we do this in both branches:

    categories.pop()

**Comment by johnlees** [comment] 2018-02-06 15:06
Yeah, thought we must have handled that... Will have to take a look at the data I think.

I'll merge ff014fb into version2

**Comment by shimbalama** [comment] 2018-02-06 23:01
Hi John, Marco,

Here's all the files I've been using. The second col of the co_vars is what I'm most confused about. This one is modelled after your example but I've tried many things there in other tests.

Thanks for your help guys!

Liam
[pyseer.tar.gz](https://github.com/mgalardini/pyseer/files/1701119/pyseer.tar.gz)

**Comment by shimbalama** [comment] 2018-02-07 01:21
Hi again John, Marco, 

After having gone over the the way I ran the previous version of SEER it occurred to me that I may have made the distance matrix/population structure wrong. 

I didn't use the provided square_mash command. I used a SNP distance matrix from Nullarbor where each pairwise SNP distance is divided by the total SNP count. Is that what square_mash does or have I missed something? If so can you please explain what the samples.msh file is and how to generate it?

Regards,
Liam

**Comment by johnlees** [comment] 2018-02-07 14:36
@shimbalama you will be able to use the matrix from Nullarbor, as long as the rows and columns are named in the same way as ours (see https://github.com/mgalardini/pyseer/blob/master/test/distances.tsv.gz) for an example.

To generate this matrix from mash instead, first of all run `mash sketch` on all your assemblies, then use `square_mash`:
```
mash sketch -o samples *.fa
mash dist samples.msh samples.msh | square_mash > mash.tsv
```

**Comment by shimbalama** [comment] 2018-02-15 02:24
Hi @johnlees and @mgalardini ,

I've now successfully run pyseer twice, once with covars once without. Everything worked well, except I got the same results from both runs. I expect theres something wrong with my file format (attached). 

I'd greatly appreciate it if you could hav a quick look and see if you can see what I'm doing wrong. Its modelled on the example you gave (first col sample name, second col sample number (is this column necessary? Doesn't seem to work without it though) and third col country (converted to a number -e, Australia 1, NZ 2 etc))
[co_vars.txt](https://github.com/mgalardini/pyseer/files/1726242/co_vars.txt)

Thanks!
Liam

**Comment by shimbalama** [comment] 2018-02-26 01:37
Hi guys,

Just wondering if you had a chance to look at the above?

Liam

**Comment by johnlees** [comment] 2018-02-26 15:07
Hi Liam,
Sorry for taking a while to get back to you.
Did you use both the covariates flags, i.e.
```
--covariates co_var.txt --use-covariates 2
```
You should get extra columns in the output with all the beta values of the covariate categories.

The example needs to be `--use-covariates 2q 3` to treat the second column as continuous, otherwise there is a separate covariate category for every sample.

If you're still having trouble could you send me your input files (just the first few lines of the variants will do) and the exact command you use?

Cheers,
John

**Comment by mgalardini** [comment] 2018-02-26 15:14
Hi Liam,

as far as I can see everything looks good with your covariates files. Would you mind sending a few examples over for us to test? A few kmers, the distance matrix and the phenotypes would suffice, thanks!

Best,
Marco

p.s. please note that we recently update `pyseer`; would you also mind trying if the new version magically resolves your issue?

**Closed** 2019-01-14 15:04 UTC
Labels: question
