### ISSUE TITLE
IndexError-list index out of range

### ISSUE THREAD

**Issue by buihoangphuc412** [mgalardini/pyseer#145] opened 2021-04-21 13:09 UTC
I ran this command 
annotate_hits_pyseer significant_kmers_amox.txt references.txt annotated_kmers_amox.txt
and get error: 
100 kmers remain
Reference 1
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -v 1 -k 8 CHC97.fasta /media/sf_Biolinux/Antibiotic project/pyseer/remaining_kmers.fa
[main] Real time: 0.125 sec; CPU: 0.114 sec
Traceback (most recent call last):
  File "/home/manager/miniconda3/envs/test/bin/annotate_hits_pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/manager/miniconda3/envs/test/lib/python3.7/site-packages/pyseer/kmer_mapping/annotate_hits.py", line 179, in main
    up_genes = extract_genes(sorted_query.closest(b=ref_annotation, s=False, D="ref", iu=True, stream=True))
  File "/home/manager/miniconda3/envs/test/lib/python3.7/site-packages/pyseer/kmer_mapping/annotate_hits.py", line 52, in extract_genes
    for tag in match.fields[15].split(";"):
IndexError: list index out of range

I attached files for running
[references.txt](https://github.com/mgalardini/pyseer/files/6351045/references.txt)
[significant_kmers_amox.txt](https://github.com/mgalardini/pyseer/files/6351046/significant_kmers_amox.txt)

**Comment by johnlees** [comment] 2021-04-26 11:48
@mgalardini The range error seems common in this script, whenever bwa gives something with surprising formatting. Maybe we should put it in a try/catch?

**Comment by mgalardini** [comment] 2021-04-26 11:54
Agreed! Will try to implement something in the next couple of days, we are due a new version as well I think

**Comment by mgalardini** [comment] 2021-04-27 10:14
@buihoangphuc412 would you mind sharing the fasta and gff file for sample `CHC97`?

Thanks

**Comment by buihoangphuc412** [comment] 2021-04-27 11:33
I attached the files.
Thanks

Vào Th 3, 27 thg 4, 2021 vào lúc 19:14 Marco Galardini <
***@***.***> đã viết:

**Comment by mgalardini** [comment] 2021-04-27 11:40
Sorry, I don't see them, you may need to attach them by replying to the message using Github's interface

**Comment by buihoangphuc412** [comment] 2021-04-27 11:51
[CHC97.zip](https://github.com/mgalardini/pyseer/files/6384259/CHC97.zip)

**Comment by mgalardini** [comment] 2021-04-27 12:11
Which version of pyseer are you using? I can't reproduce the error using pyseer v1.3.4 or from the latest commit

**Comment by buihoangphuc412** [comment] 2021-04-27 12:22
I used the new version
pyseer --version
pyseer 1.3.6

**Comment by mgalardini** [comment] 2021-04-27 12:33
Tried that too, but I'm not encountering any error.  Let's make sure we have no other version mismatch; here's the version of the other relevant libraries/software:

- python 3.9.2
- pybedtools 0.8.2
- bwa 0.7.17-r1188

My output (truncated before it fails because I don't have the other references):

```
~/workspace/pyseer/issue_145$ annotate_hits_pyseer significant_kmers_amox.txt references.txt output
100 kmers remain                                                                                         
Reference 1                                                                                              
[main] Version: 0.7.17-r1188                                                                             
[main] CMD: bwa mem -v 1 -k 8 CHC97.fasta /home/m/workspace/pyseer/issue_145/remaining_kmers.fa
[main] Real time: 0.060 sec; CPU: 0.061 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs                                                                                                                                                                     
[main] Version: 0.7.17-r1188
[main] CMD: bwa fastmap -w 100 -l 9 CHC97.fasta /home/m/workspace/pyseer/issue_145/remaining_kmers.fa
[main] Real time: 0.008 sec; CPU: 0.010 sec                                                              
71 kmers remain
Draft reference 2
```

**Comment by mgalardini** [comment] 2021-06-03 11:29
Closing for lack of follow-up replies and could not reproduce

**Closed by mgalardini** 2021-06-03 11:29 UTC
Labels: improvements, scripts
