### ISSUE TITLE
no significant genes using --vcf mode

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#166] opened 2021-08-23 15:44 UTC
Hello,

I am using pyseer to identify significant genes associated with continuous phenotypes by using the --vcf mode. But pyseer doesnt identify any significant gene :/

This is the command used and the output on the screen:
![image](https://user-images.githubusercontent.com/74925521/130475284-15a0a82c-1675-4434-b3a6-7665fa3008f3.png)

Screenshot of the phenotype file:
![image](https://user-images.githubusercontent.com/74925521/130476066-43da5331-7fd5-44b4-a125-1cdf87fe388b.png)

Screenshot of the vcf file:
![image](https://user-images.githubusercontent.com/74925521/130476637-a3113423-9e67-4ad1-9456-839d6d2f9597.png)

I would appreciate any help :) 

Thank you in advance!

**Comment by johnlees** [comment] 2021-08-24 08:18
All of your variants are being filtered out and not being tested. This is almost always caused by a mismatch between the sample names in the variant file (the VCF header in your case) and the phenotype file. Can you confirm whether the samples in the VCF file have the same names ERR133685 etc?

Also, I can see in your VCF file most positions are listed as missing '.' (which is the default when single sample VCFs are merged). You may wish to fill these in as ref '0'. See the 'missing2ref' plugin in bcftools

**Comment by annarerra** [comment] 2021-08-24 09:22
Hello John!

the names were ok but it was a problem of the positions listed as missing.
I used the 'setGT' (missing2ref has been deprecated by setGT) and now it is working!!
![image](https://user-images.githubusercontent.com/74925521/130591789-f79498e4-62ec-4f14-87c9-b7ada73d1f5b.png)

Thanks a lot for your help :) :)

**Closed** 2021-08-24 09:24 UTC
